#!/bin/bash
set -e

sudo chown -R docker:apache /var/moodledata/
sudo chmod -R 775 /var/moodledata/

#start up cron
sudo /sbin/crond

# Make sure we're not confused by old, incompletely-shutdown httpd context after restarting the container.
# httpd won't start correctly if it thinks it is already running. ref: https://github.com/CentOS/CentOS-Dockerfiles/blob/master/httpd/centos7/run-httpd.sh
sudo rm -rf /run/httpd/* /tmp/httpd*

exec sudo /usr/sbin/apachectl -DFOREGROUND
